// This seed script is deprecated.
// Challenges are now generated by AI daily via /api/challenges.
// Use scripts/seed-languages.ts to seed languages and categories.
//
// To seed: DATABASE_URL=... bun run scripts/seed-languages.ts

export {};
